# Low-Power Optimization Profile

# Enable Power Management (deep sleep EM2)
CONFIG_PM=y

# Disable All Logging, Console, and Serial Drivers
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
